SIF: Sif::Indentation Class Reference
Sif::Indentation Class Reference
#include <ASTNodes.hpp>
Public Member Functions
Indentation ()
Indentation (const int &_tab_width)
Indentation (const int &_tab_width, const bool &_use_spaces)
Indentation (const int &_tab_width, const bool &_use_spaces, const int &_current_tab_width)
Indentation (const Indentation &_indentation)
std::string str () const
Indentation & operator++ ()
Indentation operator++ (int)
Indentation & operator-- ()
Indentation operator-- (int)
Indentation & operator= (const Indentation &_indentation)
Private Attributes
int tab_width
bool use_spaces
int current_tab_width
Detailed Description
Definition at line 208 of file ASTNodes.hpp.
Constructor & Destructor Documentation
Sif::Indentation::Indentation () inline
Definition at line 210 of file ASTNodes.hpp.
 : tab_width(4), use_spaces(true), current_tab_width(0) {}
Sif::Indentation::Indentation (const int & _tab_width) inline explicit
Definition at line 211 of file ASTNodes.hpp.
 : tab_width(_tab_width), use_spaces(true), current_tab_width(0) {}
Sif::Indentation::Indentation (const int & _tab_width, const bool & _use_spaces) inline
Definition at line 212 of file ASTNodes.hpp.
 : tab_width(_tab_width), use_spaces(_use_spaces), current_tab_width(0) {}
Sif::Indentation::Indentation (const int & _tab_width, const bool & _use_spaces, const int & _current_tab_width) inline
Definition at line 213 of file ASTNodes.hpp.
References Indentation(), operator++(), operator--(), operator=(), and str().
 : tab_width(_tab_width), use_spaces(_use_spaces), current_tab_width(_current_tab_width) {}
Sif::Indentation::Indentation (const Indentation & _indentation)
Definition at line 11 of file ASTNodes.cpp.
References current_tab_width, tab_width, and use_spaces.
{
     tab_width = _indentation.tab_width;
     use_spaces = _indentation.use_spaces;
     current_tab_width = _indentation.current_tab_width;
 }
Member Function Documentation
Indentation & Sif::Indentation::operator++ ()
Definition at line 17 of file ASTNodes.cpp.
References current_tab_width, and tab_width.
{
     current_tab_width += tab_width;
     return *this;
 }
Indentation Sif::Indentation::operator++ (int)
Definition at line 22 of file ASTNodes.cpp.
{
     Indentation result(*this);
     ++(*this);
     return result;
 }
Indentation & Sif::Indentation::operator-- ()
Definition at line 28 of file ASTNodes.cpp.
References current_tab_width, and tab_width.
{
     current_tab_width -= tab_width;
     if (current_tab_width < 0) current_tab_width = 0;
     return *this;
 }
Indentation Sif::Indentation::operator-- (int)
Definition at line 34 of file ASTNodes.cpp.
{
     Indentation result(*this);
     --(*this);
     return result;
 }
Indentation & Sif::Indentation::operator= (const Indentation & _indentation)
Definition at line 40 of file ASTNodes.cpp.
References current_tab_width, tab_width, and use_spaces.
{
     tab_width = _indentation.tab_width;
     use_spaces = _indentation.use_spaces;
     current_tab_width = _indentation.current_tab_width;
     return *this;
 }
std::string Sif::Indentation::str () const
Definition at line 47 of file ASTNodes.cpp.
References current_tab_width, and use_spaces.
{
     std::string result;
     for (int i = 0; i < current_tab_width; ++i) {
         result = result + (use_spaces? ' ': '\t');
     }
     return result;
 }
Member Data Documentation
int Sif::Indentation::current_tab_width private
Definition at line 224 of file ASTNodes.hpp.
int Sif::Indentation::tab_width private
Definition at line 222 of file ASTNodes.hpp.
bool Sif::Indentation::use_spaces private
Definition at line 223 of file ASTNodes.hpp.
The documentation for this class was generated from the following files:
ASTNodes.hpp
ASTNodes.cpp