SIF: Sif Namespace Reference
Sif Namespace Reference
Classes
class ArrayTypeNameNode
class AssignmentNode
class ASTAnalyser
class ASTNode
class BinaryOperationNode
class BlockNode
class BreakNode
class ConditionalNode
class ContinueNode
class ContractDefinitionNode
class DoWhileStatementNode
class ElementaryTypeNameExpressionNode
class ElementaryTypeNameNode
class EmitStatementNode
class EnumDefinitionNode
class EnumValueNode
class EventDefinitionNode
class ExpressionStatementNode
class ForStatementNode
class FunctionCallNode
class FunctionDefinitionNode
class FunctionTypeNameNode
class IdentifierNode
class IfStatementNode
class ImportDirectiveNode
class Indentation
class IndexAccessNode
class InlineAssemblyNode
class LiteralNode
class MappingNode
class MemberAccessNode
class ModifierDefinitionNode
class ModifierInvocationNode
class NewExpresionNode
class ParameterListNode
class PlaceHolderStatement
class PragmaDirectiveNode
class ReturnNode
class RootNode
class StructDefinitionNode
class ThrowNode
class TupleExpressionNode
class UnaryOperationNode
class UserDefinedTypeNameNode
class UsingForDirectiveNode
class VariableDeclarationNode
class VariableDeclarationStatementNode
class WhileStatementNode
Typedefs
typedef std::vector< std::string > Literals
typedef std::shared_ptr< Indentation > IndentationPtr
typedef std::shared_ptr< ASTNode > ASTNodePtr
typedef std::shared_ptr< RootNode > RootNodePtr
typedef std::shared_ptr< PragmaDirectiveNode > PragmaDirectiveNodePtr
typedef std::shared_ptr< ImportDirectiveNode > ImportDirectiveNodePtr
typedef std::shared_ptr< UsingForDirectiveNode > UsingForDirectiveNodePtr
typedef std::shared_ptr< VariableDeclarationNode > VariableDeclarationNodePtr
typedef std::shared_ptr< VariableDeclarationStatementNode > VariableDeclarationStatementNodePtr
typedef std::shared_ptr< IdentifierNode > IdentifierNodePtr
typedef std::shared_ptr< StructDefinitionNode > StructDefinitionNodePtr
typedef std::shared_ptr< ParameterListNode > ParameterListNodePtr
typedef std::shared_ptr< EventDefinitionNode > EventDefinitionNodePtr
typedef std::shared_ptr< ExpressionStatementNode > ExpressionStatementNodePtr
typedef std::shared_ptr< EmitStatementNode > EmitStatementNodePtr
typedef std::shared_ptr< IndexAccessNode > IndexAccessNodePtr
typedef std::shared_ptr< BinaryOperationNode > BinaryOperationNodePtr
typedef std::shared_ptr< UnaryOperationNode > UnaryOperationNodePtr
typedef std::shared_ptr< LiteralNode > LiteralNodePtr
typedef std::shared_ptr< TupleExpressionNode > TupleExpressionNodePtr
typedef std::shared_ptr< BlockNode > BlockNodePtr
typedef std::shared_ptr< ReturnNode > ReturnNodePtr
typedef std::shared_ptr< ModifierDefinitionNode > ModifierDefinitionNodePtr
typedef std::shared_ptr< ModifierInvocationNode > ModifierInvocationNodePtr
typedef std::shared_ptr< FunctionDefinitionNode > FunctionDefinitionNodePtr
typedef std::shared_ptr< FunctionCallNode > FunctionCallNodePtr
typedef std::shared_ptr< MemberAccessNode > MemberAccessNodePtr
typedef std::shared_ptr< ElementaryTypeNameExpressionNode > ElementaryTypeNameExpressionNodePtr
typedef std::shared_ptr< ContractDefinitionNode > ContractDefinitionNodePtr
typedef std::shared_ptr< IfStatementNode > IfStatementNodePtr
typedef std::shared_ptr< DoWhileStatementNode > DoWhileStatementNodePtr
typedef std::shared_ptr< WhileStatementNode > WhileStatementNodePtr
typedef std::shared_ptr< ForStatementNode > ForStatementNodePtr
typedef std::shared_ptr< ConditionalNode > ConditionalNodePtr
typedef std::shared_ptr< AssignmentNode > AssignmentNodePtr
typedef std::shared_ptr< BreakNode > BreakNodePtr
typedef std::shared_ptr< ContinueNode > ContinueNodePtr
typedef std::shared_ptr< NewExpresionNode > NewExpresionNodePtr
typedef std::shared_ptr< EnumDefinitionNode > EnumDefinitionNodePtr
typedef std::shared_ptr< EnumValueNode > EnumValueNodePtr
typedef std::shared_ptr< ThrowNode > ThrowNodePtr
typedef std::shared_ptr< PlaceHolderStatement > PlaceHolderStatementPtr
typedef std::shared_ptr< MappingNode > MappingNodePtr
typedef std::shared_ptr< ElementaryTypeNameNode > ElementaryTypeNameNodePtr
typedef std::shared_ptr< UserDefinedTypeNameNode > UserDefinedTypeNameNodePtr
typedef std::shared_ptr< FunctionTypeNameNode > FunctionTypeNameNodePtr
typedef std::shared_ptr< ArrayTypeNameNode > ArrayTypeNameNodePtr
typedef std::shared_ptr< InlineAssemblyNode > InlineAssemblyNodePtr
Enumerations
enum NodeType {
NodeTypeSourceUnit, NodeTypeRoot, NodeTypePragmaDirective, NodeTypeImportDirective,
NodeTypeUsingForDirective, NodeTypeVariableDeclaration, NodeTypeStructDefinition, NodeTypeParameterList,
NodeTypeEventDefinition, NodeTypeBlockNode, NodeTypeFunctionDefinition, NodeTypeContractDefinition,
NodeTypeFunctionCall, NodeTypeEnumDefinition, NodeTypeEnumValue, NodeTypeModifierDefinition,
NodeTypeModifierInvocation, NodeTypeMapping, NodeTypeInlineAssembly, NodeTypePlaceholderStatement,
NodeTypeIfStatement, NodeTypeDoWhileStatement, NodeTypeWhileStatement, NodeTypeForStatement,
NodeTypeContinue, NodeTypeBreak, NodeTypeReturn, NodeTypeThrow,
NodeTypeEmitStatement, NodeTypeVariableDeclarationStatement, NodeTypeExpressionStatement, NodeTypeConditional,
NodeTypeAssignment, NodeTypeTupleExpression, NodeTypeUnaryOperation, NodeTypeBinaryOperation,
NodeTypeNewExpression, NodeTypeMemberAccess, NodeTypeIndexAccess, NodeTypeIdentifier,
NodeTypeElementaryTypeNameExpression, NodeTypeLiteral, NodeTypeElementaryTypeName, NodeTypeUserDefinedTypeName,
NodeTypeFunctionTypeName, NodeTypeArrayTypeName
}
Functions
std::ostream & operator<< (std::ostream &_os, const Indentation &_indentation)
std::string operator+ (const std::string &_str, const Indentation &_indentation)
std::string operator+ (const Indentation &_indentation, const std::string &_str)
void before (std::string arg)
void visit (ASTNode *node)
void after ()
Variables
const std::string TokenSourceUnit = "SourceUnit"
const std::string TokenPragmaDirective = "PragmaDirective"
const std::string TokenImportDirective = "ImportDirective"
const std::string TokenContractDefinition = "ContractDefinition"
const std::string TokenInheritanceSpecifier = "InheritanceSpecifier"
const std::string TokenUsingForDirective = "UsingForDirective"
const std::string TokenStructDefinition = "StructDefinition"
const std::string TokenEnumDefinition = "EnumDefinition"
const std::string TokenEnumValue = "EnumValue"
const std::string TokenParameterList = "ParameterList"
const std::string TokenFunctionDefinition = "FunctionDefinition"
const std::string TokenVariableDeclaration = "VariableDeclaration"
const std::string TokenModifierDefinition = "ModifierDefinition"
const std::string TokenModifierInvocation = "ModifierInvocation"
const std::string TokenEventDefinition = "EventDefinition"
const std::string TokenElementaryTypeName = "ElementaryTypeName"
const std::string TokenUserDefinedTypeName = "UserDefinedTypeName"
const std::string TokenFunctionTypeName = "FunctionTypeName"
const std::string TokenMapping = "Mapping"
const std::string TokenArrayTypeName = "ArrayTypeName"
const std::string TokenInlineAssembly = "InlineAssembly"
const std::string TokenBlock = "Block"
const std::string TokenPlaceholderStatement = "PlaceholderStatement"
const std::string TokenIfStatement = "IfStatement"
const std::string TokenDoWhileStatement = "DoWhileStatement"
const std::string TokenWhileStatement = "WhileStatement"
const std::string TokenForStatement = "ForStatement"
const std::string TokenContinue = "Continue"
const std::string TokenBreak = "Break"
const std::string TokenReturn = "Return"
const std::string TokenThrow = "Throw"
const std::string TokenEmitStatement = "EmitStatement"
const std::string TokenVariableDeclarationStatement = "VariableDeclarationStatement"
const std::string TokenExpressionStatement = "ExpressionStatement"
const std::string TokenConditional = "Conditional"
const std::string TokenAssignment = "Assignment"
const std::string TokenTupleExpression = "TupleExpression"
const std::string TokenUnaryOperation = "UnaryOperation"
const std::string TokenBinaryOperation = "BinaryOperation"
const std::string TokenFunctionCall = "FunctionCall"
const std::string TokenNewExpression = "NewExpression"
const std::string TokenMemberAccess = "MemberAccess"
const std::string TokenIndexAccess = "IndexAccess"
const std::string TokenIdentifier = "Identifier"
const std::string TokenElementaryTypeNameExpression = "ElementaryTypeNameExpression"
const std::string TokenLiteral = "Literal,"
const std::string TokenLiterals = "Literals"
const std::string TokenSource = "Source:"
const std::string TokenType = "Type:"
const std::list< std::string > TokenList
const std::list< std::string > ExpressionTokenList
const std::list< std::string > StatementTokenList
Typedef Documentation
typedef std::shared_ptr<ArrayTypeNameNode> Sif::ArrayTypeNameNodePtr
Definition at line 910 of file ASTNodes.hpp.
typedef std::shared_ptr<AssignmentNode> Sif::AssignmentNodePtr
Definition at line 776 of file ASTNodes.hpp.
typedef std::shared_ptr<ASTNode> Sif::ASTNodePtr
Definition at line 232 of file ASTNodes.hpp.
typedef std::shared_ptr<BinaryOperationNode> Sif::BinaryOperationNodePtr
Definition at line 468 of file ASTNodes.hpp.
typedef std::shared_ptr<BlockNode> Sif::BlockNodePtr
Definition at line 524 of file ASTNodes.hpp.
typedef std::shared_ptr<BreakNode> Sif::BreakNodePtr
Definition at line 783 of file ASTNodes.hpp.
typedef std::shared_ptr<ConditionalNode> Sif::ConditionalNodePtr
Definition at line 758 of file ASTNodes.hpp.
typedef std::shared_ptr<ContinueNode> Sif::ContinueNodePtr
Definition at line 790 of file ASTNodes.hpp.
typedef std::shared_ptr<ContractDefinitionNode> Sif::ContractDefinitionNodePtr
Definition at line 674 of file ASTNodes.hpp.
typedef std::shared_ptr<DoWhileStatementNode> Sif::DoWhileStatementNodePtr
Definition at line 705 of file ASTNodes.hpp.
typedef std::shared_ptr<ElementaryTypeNameExpressionNode> Sif::ElementaryTypeNameExpressionNodePtr
Definition at line 647 of file ASTNodes.hpp.
typedef std::shared_ptr<ElementaryTypeNameNode> Sif::ElementaryTypeNameNodePtr
Definition at line 871 of file ASTNodes.hpp.
typedef std::shared_ptr<EmitStatementNode> Sif::EmitStatementNodePtr
Definition at line 434 of file ASTNodes.hpp.
typedef std::shared_ptr<EnumDefinitionNode> Sif::EnumDefinitionNodePtr
Definition at line 817 of file ASTNodes.hpp.
typedef std::shared_ptr<EnumValueNode> Sif::EnumValueNodePtr
Definition at line 828 of file ASTNodes.hpp.
typedef std::shared_ptr<EventDefinitionNode> Sif::EventDefinitionNodePtr
Definition at line 412 of file ASTNodes.hpp.
typedef std::shared_ptr<ExpressionStatementNode> Sif::ExpressionStatementNodePtr
Definition at line 423 of file ASTNodes.hpp.
typedef std::shared_ptr<ForStatementNode> Sif::ForStatementNodePtr
Definition at line 741 of file ASTNodes.hpp.
typedef std::shared_ptr<FunctionCallNode> Sif::FunctionCallNodePtr
Definition at line 622 of file ASTNodes.hpp.
typedef std::shared_ptr<FunctionDefinitionNode> Sif::FunctionDefinitionNodePtr
Definition at line 605 of file ASTNodes.hpp.
typedef std::shared_ptr<FunctionTypeNameNode> Sif::FunctionTypeNameNodePtr
Definition at line 896 of file ASTNodes.hpp.
typedef std::shared_ptr<IdentifierNode> Sif::IdentifierNodePtr
Definition at line 368 of file ASTNodes.hpp.
typedef std::shared_ptr<IfStatementNode> Sif::IfStatementNodePtr
Definition at line 691 of file ASTNodes.hpp.
typedef std::shared_ptr<ImportDirectiveNode> Sif::ImportDirectiveNodePtr
Definition at line 309 of file ASTNodes.hpp.
typedef std::shared_ptr<Indentation> Sif::IndentationPtr
Definition at line 226 of file ASTNodes.hpp.
typedef std::shared_ptr<IndexAccessNode> Sif::IndexAccessNodePtr
Definition at line 448 of file ASTNodes.hpp.
typedef std::shared_ptr<InlineAssemblyNode> Sif::InlineAssemblyNodePtr
Definition at line 921 of file ASTNodes.hpp.
typedef std::shared_ptr<LiteralNode> Sif::LiteralNodePtr
Definition at line 496 of file ASTNodes.hpp.
typedef std::vector<std::string> Sif::Literals
Definition at line 206 of file ASTNodes.hpp.
typedef std::shared_ptr<MappingNode> Sif::MappingNodePtr
Definition at line 860 of file ASTNodes.hpp.
typedef std::shared_ptr<MemberAccessNode> Sif::MemberAccessNodePtr
Definition at line 636 of file ASTNodes.hpp.
typedef std::shared_ptr<ModifierDefinitionNode> Sif::ModifierDefinitionNodePtr
Definition at line 554 of file ASTNodes.hpp.
typedef std::shared_ptr<ModifierInvocationNode> Sif::ModifierInvocationNodePtr
Definition at line 572 of file ASTNodes.hpp.
typedef std::shared_ptr<NewExpresionNode> Sif::NewExpresionNodePtr
Definition at line 801 of file ASTNodes.hpp.
typedef std::shared_ptr<ParameterListNode> Sif::ParameterListNodePtr
Definition at line 398 of file ASTNodes.hpp.
typedef std::shared_ptr<PlaceHolderStatement> Sif::PlaceHolderStatementPtr
Definition at line 846 of file ASTNodes.hpp.
typedef std::shared_ptr<PragmaDirectiveNode> Sif::PragmaDirectiveNodePtr
Definition at line 288 of file ASTNodes.hpp.
typedef std::shared_ptr<ReturnNode> Sif::ReturnNodePtr
Definition at line 536 of file ASTNodes.hpp.
typedef std::shared_ptr<RootNode> Sif::RootNodePtr
Definition at line 277 of file ASTNodes.hpp.
typedef std::shared_ptr<StructDefinitionNode> Sif::StructDefinitionNodePtr
Definition at line 385 of file ASTNodes.hpp.
typedef std::shared_ptr<ThrowNode> Sif::ThrowNodePtr
Definition at line 835 of file ASTNodes.hpp.
typedef std::shared_ptr<TupleExpressionNode> Sif::TupleExpressionNodePtr
Definition at line 510 of file ASTNodes.hpp.
typedef std::shared_ptr<UnaryOperationNode> Sif::UnaryOperationNodePtr
Definition at line 485 of file ASTNodes.hpp.
typedef std::shared_ptr<UserDefinedTypeNameNode> Sif::UserDefinedTypeNameNodePtr
Definition at line 882 of file ASTNodes.hpp.
typedef std::shared_ptr<UsingForDirectiveNode> Sif::UsingForDirectiveNodePtr
Definition at line 324 of file ASTNodes.hpp.
typedef std::shared_ptr<VariableDeclarationNode> Sif::VariableDeclarationNodePtr
Definition at line 342 of file ASTNodes.hpp.
typedef std::shared_ptr<VariableDeclarationStatementNode> Sif::VariableDeclarationStatementNodePtr
Definition at line 357 of file ASTNodes.hpp.
typedef std::shared_ptr<WhileStatementNode> Sif::WhileStatementNodePtr
Definition at line 720 of file ASTNodes.hpp.
Enumeration Type Documentation
enum Sif::NodeType
Enumerator
NodeTypeSourceUnit
NodeTypeRoot
NodeTypePragmaDirective
NodeTypeImportDirective
NodeTypeUsingForDirective
NodeTypeVariableDeclaration
NodeTypeStructDefinition
NodeTypeParameterList
NodeTypeEventDefinition
NodeTypeBlockNode
NodeTypeFunctionDefinition
NodeTypeContractDefinition
NodeTypeFunctionCall
NodeTypeEnumDefinition
NodeTypeEnumValue
NodeTypeModifierDefinition
NodeTypeModifierInvocation
NodeTypeMapping
NodeTypeInlineAssembly
NodeTypePlaceholderStatement
NodeTypeIfStatement
NodeTypeDoWhileStatement
NodeTypeWhileStatement
NodeTypeForStatement
NodeTypeContinue
NodeTypeBreak
NodeTypeReturn
NodeTypeThrow
NodeTypeEmitStatement
NodeTypeVariableDeclarationStatement
NodeTypeExpressionStatement
NodeTypeConditional
NodeTypeAssignment
NodeTypeTupleExpression
NodeTypeUnaryOperation
NodeTypeBinaryOperation
NodeTypeNewExpression
NodeTypeMemberAccess
NodeTypeIndexAccess
NodeTypeIdentifier
NodeTypeElementaryTypeNameExpression
NodeTypeLiteral
NodeTypeElementaryTypeName
NodeTypeUserDefinedTypeName
NodeTypeFunctionTypeName
NodeTypeArrayTypeName
Definition at line 157 of file ASTNodes.hpp.
               {
     NodeTypeSourceUnit,
     NodeTypeRoot,
     NodeTypePragmaDirective,
     NodeTypeImportDirective,
     NodeTypeUsingForDirective,
     NodeTypeVariableDeclaration,
     NodeTypeStructDefinition,
     NodeTypeParameterList,
     NodeTypeEventDefinition,
     NodeTypeBlockNode,
     NodeTypeFunctionDefinition,
     NodeTypeContractDefinition,
     NodeTypeFunctionCall,
     NodeTypeEnumDefinition,
     NodeTypeEnumValue,
     NodeTypeModifierDefinition,
     NodeTypeModifierInvocation,
     NodeTypeMapping,
     NodeTypeInlineAssembly,
     NodeTypePlaceholderStatement,
     NodeTypeIfStatement,
     NodeTypeDoWhileStatement,
     NodeTypeWhileStatement,
     NodeTypeForStatement,
     NodeTypeContinue,
     NodeTypeBreak,
     NodeTypeReturn,
     NodeTypeThrow,
     NodeTypeEmitStatement,
     NodeTypeVariableDeclarationStatement,
     NodeTypeExpressionStatement,
     NodeTypeConditional,
     NodeTypeAssignment,
     NodeTypeTupleExpression,
     NodeTypeUnaryOperation,
     NodeTypeBinaryOperation,
     NodeTypeNewExpression,
     NodeTypeMemberAccess,
     NodeTypeIndexAccess,
     NodeTypeIdentifier,
     NodeTypeElementaryTypeNameExpression,
     NodeTypeLiteral,
     NodeTypeElementaryTypeName,
     NodeTypeUserDefinedTypeName,
     NodeTypeFunctionTypeName,
     NodeTypeArrayTypeName
 };
Function Documentation
void Sif::after ()
Definition at line 13 of file ASTVisitor.cpp.
              {
     return;
 }
void Sif::before (std::string arg)
Definition at line 5 of file ASTVisitor.cpp.
{
     return;
 }
std::string Sif::operator+ (const std::string & _str, const Indentation & _indentation)
Definition at line 60 of file ASTNodes.cpp.
References Sif::Indentation::str().
{
     std::string result = _str + _indentation.str();
     return result;
 }
std::string Sif::operator+ (const Indentation & _indentation, const std::string & _str)
Definition at line 65 of file ASTNodes.cpp.
References Sif::Indentation::str().
{
     std::string result = _indentation.str() + _str;
     return result;
 }
std::ostream & Sif::operator<< (std::ostream & _os, const Indentation & _indentation)
Definition at line 55 of file ASTNodes.cpp.
References Sif::Indentation::str().
{
     _os << _indentation.str();
     return _os;
 }
void Sif::visit (ASTNode * node)
Definition at line 9 of file ASTVisitor.cpp.
{
     return;
 }
Variable Documentation
const std::list<std::string> Sif::ExpressionTokenList
Initial value:
{
    TokenConditional,
    TokenAssignment,
    TokenTupleExpression,
    TokenUnaryOperation,
    TokenBinaryOperation,
    TokenFunctionCall,
    TokenNewExpression,
    TokenMemberAccess,
    TokenIndexAccess,
    TokenIdentifier,
    TokenElementaryTypeNameExpression,
    TokenLiteral
}
Definition at line 125 of file ASTNodes.hpp.
const std::list<std::string> Sif::StatementTokenList
Initial value:
{
    TokenBlock,
    TokenPlaceholderStatement,
    TokenIfStatement,
    TokenDoWhileStatement,
    TokenWhileStatement,
    TokenForStatement,
    TokenContinue,
    TokenBreak,
    TokenReturn,
    TokenThrow,
    TokenEmitStatement,
    TokenVariableDeclarationStatement,
    TokenExpressionStatement,
    TokenInlineAssembly
}
Definition at line 140 of file ASTNodes.hpp.
const std::string Sif::TokenArrayTypeName = "ArrayTypeName"
Definition at line 42 of file ASTNodes.hpp.
const std::string Sif::TokenAssignment = "Assignment"
Definition at line 58 of file ASTNodes.hpp.
const std::string Sif::TokenBinaryOperation = "BinaryOperation"
Definition at line 61 of file ASTNodes.hpp.
const std::string Sif::TokenBlock = "Block"
Definition at line 44 of file ASTNodes.hpp.
const std::string Sif::TokenBreak = "Break"
Definition at line 51 of file ASTNodes.hpp.
const std::string Sif::TokenConditional = "Conditional"
Definition at line 57 of file ASTNodes.hpp.
const std::string Sif::TokenContinue = "Continue"
Definition at line 50 of file ASTNodes.hpp.
const std::string Sif::TokenContractDefinition = "ContractDefinition"
Definition at line 26 of file ASTNodes.hpp.
const std::string Sif::TokenDoWhileStatement = "DoWhileStatement"
Definition at line 47 of file ASTNodes.hpp.
const std::string Sif::TokenElementaryTypeName = "ElementaryTypeName"
Definition at line 38 of file ASTNodes.hpp.
const std::string Sif::TokenElementaryTypeNameExpression = "ElementaryTypeNameExpression"
Definition at line 67 of file ASTNodes.hpp.
const std::string Sif::TokenEmitStatement = "EmitStatement"
Definition at line 54 of file ASTNodes.hpp.
const std::string Sif::TokenEnumDefinition = "EnumDefinition"
Definition at line 30 of file ASTNodes.hpp.
const std::string Sif::TokenEnumValue = "EnumValue"
Definition at line 31 of file ASTNodes.hpp.
const std::string Sif::TokenEventDefinition = "EventDefinition"
Definition at line 37 of file ASTNodes.hpp.
const std::string Sif::TokenExpressionStatement = "ExpressionStatement"
Definition at line 56 of file ASTNodes.hpp.
const std::string Sif::TokenForStatement = "ForStatement"
Definition at line 49 of file ASTNodes.hpp.
const std::string Sif::TokenFunctionCall = "FunctionCall"
Definition at line 62 of file ASTNodes.hpp.
const std::string Sif::TokenFunctionDefinition = "FunctionDefinition"
Definition at line 33 of file ASTNodes.hpp.
const std::string Sif::TokenFunctionTypeName = "FunctionTypeName"
Definition at line 40 of file ASTNodes.hpp.
const std::string Sif::TokenIdentifier = "Identifier"
Definition at line 66 of file ASTNodes.hpp.
const std::string Sif::TokenIfStatement = "IfStatement"
Definition at line 46 of file ASTNodes.hpp.
const std::string Sif::TokenImportDirective = "ImportDirective"
Definition at line 25 of file ASTNodes.hpp.
const std::string Sif::TokenIndexAccess = "IndexAccess"
Definition at line 65 of file ASTNodes.hpp.
const std::string Sif::TokenInheritanceSpecifier = "InheritanceSpecifier"
Definition at line 27 of file ASTNodes.hpp.
const std::string Sif::TokenInlineAssembly = "InlineAssembly"
Definition at line 43 of file ASTNodes.hpp.
const std::list<std::string> Sif::TokenList
Definition at line 73 of file ASTNodes.hpp.
const std::string Sif::TokenLiteral = "Literal,"
Definition at line 68 of file ASTNodes.hpp.
const std::string Sif::TokenLiterals = "Literals"
Definition at line 69 of file ASTNodes.hpp.
const std::string Sif::TokenMapping = "Mapping"
Definition at line 41 of file ASTNodes.hpp.
const std::string Sif::TokenMemberAccess = "MemberAccess"
Definition at line 64 of file ASTNodes.hpp.
const std::string Sif::TokenModifierDefinition = "ModifierDefinition"
Definition at line 35 of file ASTNodes.hpp.
const std::string Sif::TokenModifierInvocation = "ModifierInvocation"
Definition at line 36 of file ASTNodes.hpp.
const std::string Sif::TokenNewExpression = "NewExpression"
Definition at line 63 of file ASTNodes.hpp.
const std::string Sif::TokenParameterList = "ParameterList"
Definition at line 32 of file ASTNodes.hpp.
const std::string Sif::TokenPlaceholderStatement = "PlaceholderStatement"
Definition at line 45 of file ASTNodes.hpp.
const std::string Sif::TokenPragmaDirective = "PragmaDirective"
Definition at line 24 of file ASTNodes.hpp.
const std::string Sif::TokenReturn = "Return"
Definition at line 52 of file ASTNodes.hpp.
const std::string Sif::TokenSource = "Source:"
Definition at line 70 of file ASTNodes.hpp.
const std::string Sif::TokenSourceUnit = "SourceUnit"
Definition at line 23 of file ASTNodes.hpp.
const std::string Sif::TokenStructDefinition = "StructDefinition"
Definition at line 29 of file ASTNodes.hpp.
const std::string Sif::TokenThrow = "Throw"
Definition at line 53 of file ASTNodes.hpp.
const std::string Sif::TokenTupleExpression = "TupleExpression"
Definition at line 59 of file ASTNodes.hpp.
const std::string Sif::TokenType = "Type:"
Definition at line 71 of file ASTNodes.hpp.
const std::string Sif::TokenUnaryOperation = "UnaryOperation"
Definition at line 60 of file ASTNodes.hpp.
const std::string Sif::TokenUserDefinedTypeName = "UserDefinedTypeName"
Definition at line 39 of file ASTNodes.hpp.
const std::string Sif::TokenUsingForDirective = "UsingForDirective"
Definition at line 28 of file ASTNodes.hpp.
const std::string Sif::TokenVariableDeclaration = "VariableDeclaration"
Definition at line 34 of file ASTNodes.hpp.
const std::string Sif::TokenVariableDeclarationStatement = "VariableDeclarationStatement"
Definition at line 55 of file ASTNodes.hpp.
const std::string Sif::TokenWhileStatement = "WhileStatement"
Definition at line 48 of file ASTNodes.hpp.